  /home/eiselekd/git/dotfiles/windows:
  total used in directory 60 available 11612252
  drwxrwxr-x  4 eiselekd eiselekd 4096 sep  1 23:50 .
  drwxrwxr-x 14 eiselekd eiselekd 4096 aug 25 23:24 ..
  -rw-r--r--  1 eiselekd eiselekd  253 aug 15 18:08 check.sh
  -rw-r--r--  1 eiselekd eiselekd    0 aug 15 18:07 check.sh~
  -rw-r--r--  1 eiselekd eiselekd  834 sep  1 23:50 disableamd.sh
  -rw-r--r--  1 eiselekd eiselekd  363 aug 14 21:08 disableamd.sh~
  drwxr-xr-x  8 eiselekd eiselekd 4096 aug 14 18:15 dracut
  -rw-r--r--  1 eiselekd eiselekd 6173 aug 23 23:00 log.org
  drwxr-xr-x  7 eiselekd eiselekd 4096 sep  1 23:50 passthrough
  -rw-rw-r--  1 eiselekd eiselekd  639 aug 15 21:18 qemu.sh
  -rw-rw-r--  1 eiselekd eiselekd  720 aug 15 21:08 qemu.sh~
  -rw-r--r--  1 eiselekd eiselekd 1007 aug 14 21:05 repackage.sh
  -rw-r--r--  1 eiselekd eiselekd  157 aug 22 18:49 vfio-pci-override-vga.sh
  -rw-r--r--  1 eiselekd eiselekd  157 aug 14 21:06 vfio-pci-override-vga.sh~
  -rw-r--r--  1 eiselekd eiselekd  271 aug 14 21:05 vfio.sh~
