#!/bin/sh
if which stack 2&>1 > /dev/null; then
    exec stack ghc -- \
	 --make xmonad.hs \
	 -cpp -DSTACK \
	 -i \
	 -ilib \
	 -fforce-recomp \
	 -main-is main \
	 -v0 \
	 -o "$1"
else
    ghc --make xmonad.hs -o xmonad.o
fi
