* Setup

** T460s

Intel NVme ssd: bios version 1.22 and uefi boot

Disable trackpad:

function disable_trackpad()
{
  l=`xinput list | grep Synaptics `
  if [ ! -z "$l" ]; then
    id=`expr "$l" : '.*id=\([0-9]\+\)'`
    xinput --disable $id
  fi
}


** X60s

Figure out key pressed:
$xev
Show keymapping:
$xmodmap -pke
X60s issues keycode 166 (left-page, XF86Back) and 167 (right-page, XF86Forward)
other keyboard issue 112 and 117,

$xmodmap -e "keycode  166 = Prior NoSymbol Prior"
$xmodmap -e "keycode  167 = Next NoSymbol Next"

*** determine X60s model

if  dmesg|grep X60s >/dev/null; then
echo "found X60s"
fi

*** links
[1] https://wiki.archlinux.org/index.php/xmodmap

**  /etc/default/keyboad

XKBLAYOUT="de"

then: dpkg-reconfigure console-setup

** zfs

apt-add-repository universe
apt update
apt install --yes debootstrap gdisk zfs-initramfs

*** Partition

sgdisk -Z -n9:-8M:0 -t9:bf07 -c9:Reserved -n2:-8M:0 -t2:ef02 -c2:GRUB  -n3:-512M:0 -t3:ef00 -c3:UEFI -n1:0:0 -t1:bf01 -c1:ZFS <dev>

dd if=/dev/zero of=/dev/disk/by-id/nvme-eui.0000000001000000e4d25c4ddd934d01-part1
dd if=/dev/zero of=/dev/disk/by-id/nvme-eui.0000000001000000e4d25c4ddd934d01-part~2
dd if=/dev/zero of=/dev/disk/by-id/nvme-eui.0000000001000000e4d25c4ddd934d01-part~9
sgdisk -Z -n9:-8M:0 -t9:bf07 -c9:Reserved -n2:-8M:0 -t2:ef02 -c2:GRUB -n1:0:0 -t1:bf01 -c1:ZFS /dev/disk/by-id/nvme-eui.0000000001000000e4d25c4ddd934d01


*** pools

zfs snapshot rpool/ROOT/ubuntu/ubuntu@install-minimal
zfs list -t snapshot
zfs create rpool/home/eiselekd
zfs create -o mountpoint=/src rpool/src
zfs create -o mountpoint=/work rpool/work

*** scrubbing

zpool scrub <pool>
zpool status

*** snapshots

Take snapshot:
$zfs snapshot rpool/ROOT@date
Take snapshot recursive:
$zfs snapshot -r rpool/ROOT@date

List snapshots recursive
$zfs list -r -t snapshot rpool/ROOT
List usage:
$zfs get -H -o name,value -r used rpool/ROOT

*** links
[1] http://dotfiles.tnetconsulting.net/articles/2016/0327/ubuntu-zfs-native-root.html
[2] https://github.com/zfsonlinux/zfs/wiki/Ubuntu-17.04-Root-on-ZFS

** X11
disable trackpad:
xinput set-prop 13 "Device Enabled" 0


** acpi
acpi -b : battery life

** network

# 16.04
move eth0 (or similar if) to /etc/network/interfaces.d
decomment auto to prevent startjob systemd
#auto eth0
#iface eth0 inet dhcp

# simple
nmcli radio
nmcli device

nmcli device wifi rescan
nmcli device wifi list
nmcli device wifi connect <SSID-Name> password <wireless-password>

# status:
nmcli dev wifi list

# connect to wifi
nmcli con add con-name <myconname> ifname <ifname> type wifi ssid <ssid>
nmcli con modify MyCafe wifi-sec.key-mgmt wpa-psk
nmcli con modify MyCafe wifi-sec.psk <password>
nmcli radio wifi on
nmcli con show
nmcli con up uuid <uuid>
# unconnect
nmcli radio wifi off
nmcli con del <con-name>


*** links
[1] https://docs.fedoraproject.org/en-US/Fedora/25/html/Networking_Guide/sec-Connecting_to_a_Network_Using_nmcli.html
[2] https://nullr0ute.com/2016/09/connect-to-a-wireless-network-using-command-line-nmcli/


** systemd

# show services
systemctl status
# show past logging
journalctl
# show active logging:
journalctl -f
# show active loggin only resolved:
journalctl -f -u systemd-resolved

# services
service systemd-resolved restart
systemctl restart systemd-resolved.service
# systemd-resolved:
systemd-resolve --status
systemd-resolve www.test.com
# dns.watch:
84.200.69.80
# debug logging for systemd-resolved:
mkdir -p /etc/systemd/system/systemd-resolved.service.d
echo -e "[Service]\nEnvironment=SYSTEMD_LOG_LEVEL=debug" >> /etc/systemd/system/systemd-resolved.service.d/log-level.conf
systemctl daemon-reload
systemctl restart systemd-resolved.service

# cmdline
systemd_log_level=debug

# unbound:
sudo systemctl disable systemd-resolved
sudo systemctl stop systemd-resolved
/etc/NetworkManager/NetworkManager.conf
 : add [main] : dns=unbound
sudo systemctl enable unbound-resolvconf
sudo systemctl enable unbound

#/lib/systemd/systemd-sysv-install enable unbound


*** systemd-networkd systemd-resolved

/etc/network/interfaces to:
auto lo
iface lo inet loopback
and remove /etc/network/interfaces.d

start:

#+begin_src bash:
systemctl start systemd-networkd.service
systemctl start systemd-resolved.service
systemctl enable systemd-networkd.service
systemctl enable systemd-resolved.service
#+end_src

#+begin_src /etc/systemd/network/bridge0.netdev: 
[NetDev]
Name=br0
Kind=bridge
#+end_src

#+begin_src /etc/systemd/network/bridge.network: 
[Match]
Name=br0
[Network]
DHCP=ipv4
#+end_src

#+begin_src /etc/systemd/network/eth.network: 
[Match]
Name=en*
[Network]
Bridge=br0
#+end_src

=> all en* interfaces under bridge


*** links
[1] https://fedoraproject.org/wiki/How_to_debug_Systemd_problems
[2] http://wiki.ipfire.org/en/dns/public-servers
[3] http://www.hecticgeek.com/2017/04/ubuntu-17-04-systemd-dns-issues/

** docker
/etc/default/docker:
+ DOCKER_OPTS="--storage-driver=zfs"
service docker restart
systemctl restart docker

docker info
...
Storage Driver: zfs
...

docker run -it ubuntu  bash

*** build from Dockerfile

from dir of Dockerfile:
docker build -t <imagename> .

# create container and run interactive (-i)
docker run --name <containername> -v <hostpath>:<targetpath> -ti <imagename>
# restart container
docker start -i <containername>

*** building with docker-compose

docker-compose.yml:
docker-compose up -d
docker-compose up -d --build

teardown:
docker-compose rm --all
docker rmi <imgid>
docker rm <containeridid>


*** links
[1] https://www.youtube.com/watch?v=nDmvwevnJNc&feature=youtu.be

** kernel and zfs recompile

apt install rpm autoconf libtool uuid-dev libblkid-dev attr-dev

recompile mainline with deb-pkg:

git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
git clone https://github.com/zfsonlinux/spl
git clone https://github.com/zfsonlinux/zfs
git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

(cd linux; make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-custom)

d=`pwd`

(
 cd spl
 git checkout master
 sh autogen.sh
 ./configure --with-linux=$d/linux --with-linux-obj=$d/linux
 make -s -j `getconf _NPROCESSORS_ONLN` ; make deb
)
(
cd ../zfs
git checkout master
sh autogen.sh
./configure --with-spl=$d/spl --with-spl-obj=$d/spl --with-linux=$d/linux --with-linux-obj=$d/linux
make -s -j `getconf _NPROCESSORS_ONLN` ; make deb
)

... dpkg -i kmod-*deb : zfs-kmod-0.7.0-40_gdb4c1adaf.src.rpm


cd /lib/modules/<version>
mkdir kernel/zfs
cp -r extra/zfs/*  kernel/zfs/
cp -r extra/spl/*  kernel/zfs/
depmod -a <version>

possibly: echo zfs >> /etc/initramfs-tools/modules
update-initramfs -u

tests/functions/libzfs : 

--- a/tests/zfs-tests/tests/functional/libzfs/Makefile.am
+++ b/tests/zfs-tests/tests/functional/libzfs/Makefile.am
@@ -13,7 +13,8 @@ DEFAULT_INCLUDES += \
        -I$(top_srcdir)/lib/libspl/include
 
 many_fds_LDADD = \
-       $(top_builddir)/lib/libzfs/libzfs.la
+       $(top_builddir)/lib/libzfs/libzfs.la \
+       $(top_builddir)/lib/libzfs_core/libzfs_core.la
 

../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_load_key'
../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_promote'
../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_change_key'
../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_rollback_to'
../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_unload_key'

eiselekd@HOSTNAME:~/git/dotfiles/ubuntu$ gcc --version
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

eiselekd@HOSTNAME:~/git/dotfiles/ubuntu$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

*** zfs 7.1 patch:

diff --git a/cmd/mount_zfs/Makefile.am b/cmd/mount_zfs/Makefile.am
index bc9fb4c34..d4d7a7587 100644
--- a/cmd/mount_zfs/Makefile.am
+++ b/cmd/mount_zfs/Makefile.am
@@ -16,4 +16,5 @@ mount_zfs_SOURCES = \
 
 mount_zfs_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
-	$(top_builddir)/lib/libzfs/libzfs.la
+	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la
diff --git a/cmd/zdb/Makefile.am b/cmd/zdb/Makefile.am
index ea6806b2c..4685bec20 100644
--- a/cmd/zdb/Makefile.am
+++ b/cmd/zdb/Makefile.am
@@ -15,4 +15,5 @@ zdb_SOURCES = \
 zdb_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
 	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la \
 	$(top_builddir)/lib/libzpool/libzpool.la
diff --git a/cmd/zed/Makefile.am b/cmd/zed/Makefile.am
index 53d5aa71c..fbd650f4e 100644
--- a/cmd/zed/Makefile.am
+++ b/cmd/zed/Makefile.am
@@ -42,7 +42,8 @@ zed_SOURCES = $(ZED_SRC) $(FMA_SRC)
 zed_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
 	$(top_builddir)/lib/libuutil/libuutil.la \
-	$(top_builddir)/lib/libzfs/libzfs.la
+	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la
 
 zed_LDADD += -lrt
 zed_LDFLAGS = -pthread
diff --git a/cmd/zhack/Makefile.am b/cmd/zhack/Makefile.am
index f720e8286..12c0e0a4d 100644
--- a/cmd/zhack/Makefile.am
+++ b/cmd/zhack/Makefile.am
@@ -12,4 +12,5 @@ zhack_SOURCES = \
 zhack_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
 	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la \
 	$(top_builddir)/lib/libzpool/libzpool.la
diff --git a/cmd/zinject/Makefile.am b/cmd/zinject/Makefile.am
index b709a2f5a..b50114f23 100644
--- a/cmd/zinject/Makefile.am
+++ b/cmd/zinject/Makefile.am
@@ -14,4 +14,5 @@ zinject_SOURCES = \
 zinject_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
 	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la \
 	$(top_builddir)/lib/libzpool/libzpool.la
diff --git a/cmd/zpool/Makefile.am b/cmd/zpool/Makefile.am
index d7e1741c1..e2ee34137 100644
--- a/cmd/zpool/Makefile.am
+++ b/cmd/zpool/Makefile.am
@@ -16,7 +16,8 @@ zpool_SOURCES = \
 zpool_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
 	$(top_builddir)/lib/libuutil/libuutil.la \
-	$(top_builddir)/lib/libzfs/libzfs.la
+	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la 
 
 zpool_LDADD += -lm $(LIBBLKID)
 
diff --git a/cmd/zstreamdump/Makefile.am b/cmd/zstreamdump/Makefile.am
index f80b5018e..1ec2daee1 100644
--- a/cmd/zstreamdump/Makefile.am
+++ b/cmd/zstreamdump/Makefile.am
@@ -11,4 +11,5 @@ zstreamdump_SOURCES = \
 
 zstreamdump_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
-	$(top_builddir)/lib/libzfs/libzfs.la
+	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la
diff --git a/cmd/ztest/Makefile.am b/cmd/ztest/Makefile.am
index 930a7ec3a..c911a9ce8 100644
--- a/cmd/ztest/Makefile.am
+++ b/cmd/ztest/Makefile.am
@@ -17,6 +17,7 @@ ztest_SOURCES = \
 ztest_LDADD = \
 	$(top_builddir)/lib/libnvpair/libnvpair.la \
 	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la \
 	$(top_builddir)/lib/libzpool/libzpool.la
 
 ztest_LDADD += -lm
diff --git a/tests/zfs-tests/tests/functional/libzfs/Makefile.am b/tests/zfs-tests/tests/functional/libzfs/Makefile.am
index d885bc1ab..642dd1472 100644
--- a/tests/zfs-tests/tests/functional/libzfs/Makefile.am
+++ b/tests/zfs-tests/tests/functional/libzfs/Makefile.am
@@ -13,7 +13,8 @@ DEFAULT_INCLUDES += \
 	-I$(top_srcdir)/lib/libspl/include
 
 many_fds_LDADD = \
-	$(top_builddir)/lib/libzfs/libzfs.la
+	$(top_builddir)/lib/libzfs/libzfs.la \
+	$(top_builddir)/lib/libzfs_core/libzfs_core.la
 
 pkgexec_PROGRAMS = many_fds
 many_fds_SOURCES = many_fds.c



*** zfs-initramfs : for 7.0.0

add
GRUB_CMDLINE_LINUX_DEFAULT=" boot=zfs "
to /etc/default/grub
and update-grub

cp zfs-import-cache.service /lib/systemd/system/zfs-import-cache.service
cp zfs-mount.service /lib/systemd/system/
cp zfs-share.service /lib/systemd/system/
cp zfs.target /lib/systemd/system/
cp system/zfs-zed.service /lib/systemd/system/

> change /usr/local/ prefix to / in service definitions

systemctl enable zfs-import-cache
systemctl enable zfs-mount
systemctl enable zfs-share
systemctl enable zfs.target
systemctl enable zfs-zed

*** wifi t460s

[    6.218916] iwlwifi 0000:04:00.0: no suitable firmware found!
[    6.220111] iwlwifi 0000:04:00.0: minimum version required: iwlwifi-8000C-22
[    6.221293] iwlwifi 0000:04:00.0: maximum version supported: iwlwifi-8000C-30
[    6.222504] iwlwifi 0000:04:00.0: check git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

cp linux-firmware/iwlwifi-8265-22.ucode /lib/firmware/

*** links
[1] https://wiki.ubuntu.com/KernelTeam/GitKernelBuild
[2] https://github.com/zfsonlinux/zfs/wiki/Building-ZFS

** xterm

Add support for bracket matching highlight for 3-button click

apt source xterm
suco apt build-dep xterm
cat xterm_button.c  xterm_charproc.diff xterm_ptyx.h | patch -p1 -d <xterm-dir>
cd xterm-dir
debuild -us -uc
and install package

*** .Xresources
xterm*savelines: 16384
xterm*on3Clicks: bracket


xrdb -merge .Xresources
xrdb -query
*** links
[1] https://lukas.zapletalovi.com/2013/07/hidden-gems-of-xterm.html

** eclipse

***openjdk 9 :
 1. ln -s /usr/lib/jvm/java-9-openjdk-amd64/lib /usr/lib/jvm/java-9-openjdk-amd64/conf
 2. eclipse.init:
  -vmargs
+ --add-modules=java.se.ee
  -Dosgi.requiredJavaVersion=1.8



** ipython

with cling binary snapshot: cd share/cling/Jupyter/kernel
pip install -e .
add .local/bin to PATH

jupyter notebook:
pip3 install --upgrade pip
pip3 install jupyter

** perf
 linux-4.13 and perf:
 sudo apt install  libelf-dev  libaudit-dev  libgtk2.0-dev  systemtap-sdt-dev  libgtk2.0-dev liblzma-dev libbfd-dev libdw-dev libiberty-dev binutils-dev zlib1g-dev
 cd linux-4.13/tools/perf && make

