$ zpool import
   pool: epool
     id: 15752543265619539307
  state: FAULTED
 status: One or more devices contains corrupted data.
 action: The pool cannot be imported due to damaged devices or data.
	The pool may be active on another system, but can be imported using
	the '-f' flag.
   see: http://zfsonlinux.org/msg/ZFS-8000-5E
 config:

	epool                                               FAULTED  corrupted data
	  raidz1-0                                          DEGRADED
	    ata-WDC_WD30EZRX-00D8PB0_WD-WMC4N1642572-part1  UNAVAIL  corrupted data
	    ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N1KPRKPX-part1  ONLINE
	    ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZXC1E0-part1  ONLINE

$ zpool import -FfmX  epool
cannot import 'epool': one or more devices is currently unavailable
 - F : do_rewind
 - f : ZFS_IMPORT_ANY_HOST
 - m : ZFS_IMPORT_MISSING_LOG
 - X : xtreme_rewind = B_TRUE

** ok labels :

root@eiselekd-To-be-filled-by-O-E-M:/home/eiselekd# zdb -l /dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N1KPRKPX-part1
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 5000
    name: 'epool'
    state: 0
    txg: 108340
    pool_guid: 15752543265619539307
    errata: 0
    hostname: 'eiselekd-lnx'
    top_guid: 5366409938038884073
    guid: 3063814570901399057
    vdev_children: 1
    vdev_tree:
        type: 'raidz'
        id: 0
        guid: 5366409938038884073
        nparity: 1
        metaslab_array: 35
        metaslab_shift: 36
        ashift: 12
        asize: 9001706717184
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 9231358437407247535
            path: '/dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WMC4N1642572-part1'
            whole_disk: 0
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 3063814570901399057
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N1KPRKPX-part1'
            whole_disk: 0
            DTL: 136
            create_txg: 4
        children[2]:
            type: 'disk'
            id: 2
            guid: 10884448206527621454
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZXC1E0-part1'
            whole_disk: 0
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 1
--------------------------------------------
    version: 5000
    name: 'epool'
    state: 0
    txg: 108340
    pool_guid: 15752543265619539307
    errata: 0
    hostname: 'eiselekd-lnx'
    top_guid: 5366409938038884073
    guid: 3063814570901399057
    vdev_children: 1
    vdev_tree:
        type: 'raidz'
        id: 0
        guid: 5366409938038884073
        nparity: 1
        metaslab_array: 35
        metaslab_shift: 36
        ashift: 12
        asize: 9001706717184
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 9231358437407247535
            path: '/dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WMC4N1642572-part1'
            whole_disk: 0
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 3063814570901399057
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N1KPRKPX-part1'
            whole_disk: 0
            DTL: 136
            create_txg: 4
        children[2]:
            type: 'disk'
            id: 2
            guid: 10884448206527621454
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZXC1E0-part1'
            whole_disk: 0
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 2
--------------------------------------------
    version: 5000
    name: 'epool'
    state: 0
    txg: 108340
    pool_guid: 15752543265619539307
    errata: 0
    hostname: 'eiselekd-lnx'
    top_guid: 5366409938038884073
    guid: 3063814570901399057
    vdev_children: 1
    vdev_tree:
        type: 'raidz'
        id: 0
        guid: 5366409938038884073
        nparity: 1
        metaslab_array: 35
        metaslab_shift: 36
        ashift: 12
        asize: 9001706717184
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 9231358437407247535
            path: '/dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WMC4N1642572-part1'
            whole_disk: 0
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 3063814570901399057
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N1KPRKPX-part1'
            whole_disk: 0
            DTL: 136
            create_txg: 4
        children[2]:
            type: 'disk'
            id: 2
            guid: 10884448206527621454
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZXC1E0-part1'
            whole_disk: 0
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 3
--------------------------------------------
    version: 5000
    name: 'epool'
    state: 0
    txg: 108340
    pool_guid: 15752543265619539307
    errata: 0
    hostname: 'eiselekd-lnx'
    top_guid: 5366409938038884073
    guid: 3063814570901399057
    vdev_children: 1
    vdev_tree:
        type: 'raidz'
        id: 0
        guid: 5366409938038884073
        nparity: 1
        metaslab_array: 35
        metaslab_shift: 36
        ashift: 12
        asize: 9001706717184
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 9231358437407247535
            path: '/dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WMC4N1642572-part1'
            whole_disk: 0
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 3063814570901399057
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N1KPRKPX-part1'
            whole_disk: 0
            DTL: 136
            create_txg: 4
        children[2]:
            type: 'disk'
            id: 2
            guid: 10884448206527621454
            path: '/dev/disk/by-id/ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZXC1E0-part1'
            whole_disk: 0
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data


* zfs
zpool import -N -o readonly=on -f -R /mnt/gentoo -F -T <txg>
list txg with
python zfs_revert-0.1.py  -tb=5860495360 -bs=512 /dev/sdd1
where 5860495360 is from fdisk -l

[1] https://github.com/zfsonlinux/zfs/issues/2831
[2] https://serverfault.com/questions/842955/restoring-data-after-zfs-destroy
[3] http://www.giis.co.in/Zfs_ondiskformat.pdf
[4] https://www.joyent.com/blog/zfs-forensics-recovering-files-from-a-destroyed-zpool
[5] https://github.com/limelime/cust-live-deb/issues/298
[6] https://gist.github.com/jjwhitney/baaa63144da89726e482


sources
[4] https://github.com/markus512/zfs-recover/blob/master/zfs_recover.py
[5] https://github.com/nkchenz/zfspy/tree/master/zfspy
[6] https://github.com/hiliev/py-zfs-rescue
[7] https://www.dfrws.org/sites/default/files/session-files/paper-digital_forensic_implications_of_zfs.pdf
[8] https://github.com/nkchenz/zfspy

* txg

** ata-WDC_WD30EZRX-00D8PB0_WD-WMC4N1642572-part1

TXG	TIME	TIMESTAMP	BLOCK ADDRESSES
108173	08 Feb 2018 02:24:11	1518053051	[360, 872, 5860494696, 5860495208]
108193	08 Feb 2018 02:25:59	1518053159	[264, 776, 5860494600, 5860495112]
108199	08 Feb 2018 02:26:30	1518053190	[312, 824, 5860494648, 5860495160]
108219	07 Mar 2018 16:44:43	1520437483	[472, 984, 5860494808, 5860495320]
108307	08 Mar 2018 15:58:41	1520521121	[408, 920, 5860494744, 5860495256]
108313	09 Mar 2018 14:25:03	1520601903	[456, 968, 5860494792, 5860495304]
108319	12 Mar 2018 17:33:00	1520872380	[504, 1016, 5860494840, 5860495352]
108325	14 Mar 2018 19:23:31	1521051811	[296, 808, 5860494632, 5860495144]
108331	15 Mar 2018 14:36:25	1521120985	[344, 856, 5860494680, 5860495192]
108337	15 Mar 2018 20:07:58	1521140878	[392, 904, 5860494728, 5860495240]
What is the last TXG you wish to keep?


** ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N1KPRKPX-part1


108173	08 Feb 2018 02:24:11	1518053051	[360, 872, 5860494696, 5860495208] [0x168,0x368,0x15d500d68,0x15d500f68]
108183	08 Feb 2018 02:25:05	1518053105	[440, 952, 5860494776, 5860495288] [0x1b8,0x3b8,0x15d500db8,0x15d500fb8]
108189	08 Feb 2018 02:25:37	1518053137	[488, 1000, 5860494824, 5860495336] [0x1e8,0x3e8,0x15d500de8,0x15d500fe8]
108193	08 Feb 2018 02:25:59	1518053159	[264, 776, 5860494600, 5860495112] [0x108,0x308,0x15d500d08,0x15d500f08]
108195	08 Feb 2018 02:26:10	1518053170	[280, 792, 5860494616, 5860495128] [0x118,0x318,0x15d500d18,0x15d500f18]
108199	08 Feb 2018 02:26:30	1518053190	[312, 824, 5860494648, 5860495160] [0x138,0x338,0x15d500d38,0x15d500f38]
108201	23 Feb 2018 17:34:07	1519403647	[328, 840, 5860494664, 5860495176] [0x148,0x348,0x15d500d48,0x15d500f48]
108207	23 Feb 2018 21:34:27	1519418067	[376, 888, 5860494712, 5860495224] [0x178,0x378,0x15d500d78,0x15d500f78]
108213	24 Feb 2018 18:05:03	1519491903	[424, 936, 5860494760, 5860495272] [0x1a8,0x3a8,0x15d500da8,0x15d500fa8]
108219	07 Mar 2018 16:44:43	1520437483	[472, 984, 5860494808, 5860495320] [0x1d8,0x3d8,0x15d500dd8,0x15d500fd8]
108307	08 Mar 2018 15:58:41	1520521121	[408, 920, 5860494744, 5860495256] [0x198,0x398,0x15d500d98,0x15d500f98]
108312	08 Mar 2018 15:58:47	1520521127	[448, 960, 5860494784, 5860495296] [0x1c0,0x3c0,0x15d500dc0,0x15d500fc0]
108313	09 Mar 2018 14:25:03	1520601903	[456, 968, 5860494792, 5860495304] [0x1c8,0x3c8,0x15d500dc8,0x15d500fc8]
108314	09 Mar 2018 14:25:03	1520601903	[464, 976, 5860494800, 5860495312] [0x1d0,0x3d0,0x15d500dd0,0x15d500fd0]
108316	09 Mar 2018 14:25:04	1520601904	[480, 992, 5860494816, 5860495328] [0x1e0,0x3e0,0x15d500de0,0x15d500fe0]
108318	09 Mar 2018 14:25:09	1520601909	[496, 1008, 5860494832, 5860495344] [0x1f0,0x3f0,0x15d500df0,0x15d500ff0]
108319	12 Mar 2018 17:33:00	1520872380	[504, 1016, 5860494840, 5860495352] [0x1f8,0x3f8,0x15d500df8,0x15d500ff8]
108320	12 Mar 2018 17:33:00	1520872380	[256, 768, 5860494592, 5860495104] [0x100,0x300,0x15d500d00,0x15d500f00]
108322	12 Mar 2018 17:33:01	1520872381	[272, 784, 5860494608, 5860495120] [0x110,0x310,0x15d500d10,0x15d500f10]
108324	12 Mar 2018 17:33:06	1520872386	[288, 800, 5860494624, 5860495136] [0x120,0x320,0x15d500d20,0x15d500f20]
108325	14 Mar 2018 19:23:31	1521051811	[296, 808, 5860494632, 5860495144] [0x128,0x328,0x15d500d28,0x15d500f28]
108326	14 Mar 2018 19:23:31	1521051811	[304, 816, 5860494640, 5860495152] [0x130,0x330,0x15d500d30,0x15d500f30]
108328	14 Mar 2018 19:23:32	1521051812	[320, 832, 5860494656, 5860495168] [0x140,0x340,0x15d500d40,0x15d500f40]
108330	14 Mar 2018 19:23:37	1521051817	[336, 848, 5860494672, 5860495184] [0x150,0x350,0x15d500d50,0x15d500f50]
108331	15 Mar 2018 14:36:25	1521120985	[344, 856, 5860494680, 5860495192] [0x158,0x358,0x15d500d58,0x15d500f58]
108332	15 Mar 2018 14:36:26	1521120986	[352, 864, 5860494688, 5860495200] [0x160,0x360,0x15d500d60,0x15d500f60]
108334	15 Mar 2018 14:36:26	1521120986	[368, 880, 5860494704, 5860495216] [0x170,0x370,0x15d500d70,0x15d500f70]
108336	15 Mar 2018 14:36:31	1521120991	[384, 896, 5860494720, 5860495232] [0x180,0x380,0x15d500d80,0x15d500f80]
108337	15 Mar 2018 20:07:58	1521140878	[392, 904, 5860494728, 5860495240] [0x188,0x388,0x15d500d88,0x15d500f88]

020000 b10c 00ba 0000 0000 1388 0000 0000 0000
020010 a720 0001 0000 0000 1862 ce95 26ba 66c4
020020 abbc 5aa6 0000 0000 0010 0000 0000 0000
020030 0370 6800 0001 0000 0010 0000 0000 0000
020040 0180 f800 0001 0000 0010 0000 0000 0000
020050 7c80 1021 0000 0000 0003 0003 0702 800b
020060 0000 0000 0000 0000 0000 0000 0000 0000
020070 0000 0000 0000 0000 a720 0001 0000 0000
--
021000 b10c 00ba 0000 0000 1388 0000 0000 0000
021010 a6a1 0001 0000 0000 1862 ce95 26ba 66c4
021020 a727 5a7b 0000 0000 0010 0000 0000 0000
021030 1050 300a 0002 0000 0010 0000 0000 0000
021040 1050 f80a 0002 0000 0010 0000 0000 0000
021050 1030 c00a 0003 0000 0003 0003 0702 800b
021060 0000 0000 0000 0000 0000 0000 0000 0000
021070 0000 0000 0000 0000 a6a1 0001 0000 0000
--
022000 b10c 00ba 0000 0000 1388 0000 0000 0000
022010 a722 0001 0000 0000 1862 ce95 26ba 66c4
022020 abbd 5aa6 0000 0000 0010 0000 0000 0000
022030 04b0 6800 0001 0000 0010 0000 0000 0000
022040 02b0 f800 0001 0000 0010 0000 0000 0000
022050 df00 1029 0000 0000 0003 0003 0702 800b
022060 0000 0000 0000 0000 0000 0000 0000 0000
022070 0000 0000 0000 0000 a722 0001 0000 0000
--
023000 b10c 00ba 0000 0000 1388 0000 0000 0000
023010 a6a3 0001 0000 0000 1862 ce95 26ba 66c4
023020 a732 5a7b 0000 0000 0010 0000 0000 0000
023030 11f0 300a 0002 0000 0010 0000 0000 0000
023040 11f0 f80a 0002 0000 0010 0000 0000 0000
023050 11d0 c00a 0003 0000 0003 0003 0702 800b
023060 0000 0000 0000 0000 0000 0000 0000 0000
023070 0000 0000 0000 0000 a6a3 0001 0000 0000



[['3fa0000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa0010', 'a720', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa0020', 'abbc', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'],




    25000 ub_magic = 0xbab10c
    25008 ub_version = 0x1388
    25010 ub_txg = 0x14
    25018 ub_guid_sum = 0x22807e13b4464086
    25020 ub_timestamp = 0x5203bfc9
    25028 ub_rootbp = {
        25028 blk_dva = [
            25028 {
                25028 dva_word = [ 0x1, 0x424 ]
            },
            25038 {
                25038 dva_word = [ 0x1, 0x9424 ]
            },
            25048 {
                25048 dva_word = [ 0x1, 0x12424 ]
            },
        ]


 ['3fa1000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
    25000 ub_magic = 0xbab10c
    25008 ub_version = 0x1388
 ['3fa1010', 'a6a1', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
    25010 ub_txg = 0x14
    25018 ub_guid_sum = 0x22807e13b4464086
 ['3fa1020', 'a727', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'],
    25020 ub_timestamp = 0x5203bfc9
    25028 dva_word = [ 0x1, 0x424 ]



 ['3fa2000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa2010', 'a722', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa2020', 'abbd', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'],

 ['3fa3000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa3010', 'a6a3', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa3020', 'a732', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'],

 ['3fa4000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa4010', 'a724', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa4020', 'abc2', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'],

 ['3fa5000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa5010', 'a725', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa5020', '68a3', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'],

 ['3fa6000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa6010', 'a726', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa6020', '68a3', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'],

 ['3fa7000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa7010', 'a6a7', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa7020', 'a746', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fa8000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa8010', 'a728', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa8020', '68a4', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'],
['3fa9000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fa9010', 'a6a9', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fa9020', '427f', '5a90', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3faa000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3faa010', 'a72a', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3faa020', '68a9', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fab000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fab010', 'a72b', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fab020', '76d9', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fac000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fac010', 'a72c', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fac020', '76da', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fad000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fad010', 'a68d', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fad020', 'a6bb', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fae000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fae010', 'a72e', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fae020', '76da', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3faf000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3faf010', 'a6af', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3faf020', '7ad3', '5a90', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fb0000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fb0010', 'a730', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fb0020', '76df', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fb1000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fb1010', 'a731', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fb1020', 'c48e', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fb3000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fb3010', 'a713', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fb3020', '4fa1', '5aa1', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fb5000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fb5010', 'a6b5', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fb5020', '9b3f', '5a91', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fb7000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fb7010', 'a697', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fb7020', 'a6f1', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fb8000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fb8010', 'a718', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fb8020', '4fa7', '5aa1', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fb9000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fb9010', 'a719', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fb9020', '8b2f', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fba000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
['3fba010', 'a71a', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fba020', '8b2f', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fbb000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fbb010', 'a6bb', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fbb020', '08eb', '5aa0', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fbc000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
['3fbc010', 'a71c', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
['3fbc020', '8b30', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fbd000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fbd010', 'a69d', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fbd020', 'a711', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fbe000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fbe010', 'a71e', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fbe020', '8b35', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fbf000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fbf010', 'a71f', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fbf020', 'abbc', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fe0000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fe0010', 'a720', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
['3fe0020', 'abbc', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'],
 ['3fe1000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'],
 ['3fe1010', 'a6a1', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'],
 ['3fe1020', 'a727', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'],

 ['3fe2000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe2010', 'a722', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe2020', 'abbd', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fe3000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe3010', 'a6a3', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe3020', 'a732', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fe4000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe4010', 'a724', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe4020', 'abc2', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fe5000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe5010', 'a725', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe5020', '68a3', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fe6000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe6010', 'a726', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe6020', '68a3', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fe7000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe7010', 'a6a7', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe7020', 'a746', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fe8000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe8010', 'a728', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe8020', '68a4', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fe9000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fe9010', 'a6a9', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fe9020', '427f', '5a90', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fea000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fea010', 'a72a', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fea020', '68a9', '5aa9', '0000', '0000', '0010', '0000', '0000', '0000'], ['3feb000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3feb010', 'a72b', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3feb020', '76d9', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fec000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fec010', 'a72c', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fec020', '76da', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fed000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fed010', 'a68d', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fed020', 'a6bb', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fee000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fee010', 'a72e', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fee020', '76da', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fef000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fef010', 'a6af', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fef020', '7ad3', '5a90', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ff0000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ff0010', 'a730', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ff0020', '76df', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ff1000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ff1010', 'a731', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ff1020', 'c48e', '5aaa', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ff3000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ff3010', 'a713', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ff3020', '4fa1', '5aa1', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ff5000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ff5010', 'a6b5', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ff5020', '9b3f', '5a91', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ff7000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ff7010', 'a697', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ff7020', 'a6f1', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ff8000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ff8010', 'a718', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ff8020', '4fa7', '5aa1', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ff9000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ff9010', 'a719', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ff9020', '8b2f', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ffa000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ffa010', 'a71a', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ffa020', '8b2f', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ffb000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ffb010', 'a6bb', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ffb020', '08eb', '5aa0', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ffc000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ffc010', 'a71c', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ffc020', '8b30', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ffd000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ffd010', 'a69d', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ffd020', 'a711', '5a7b', '0000', '0000', '0010', '0000', '0000', '0000'], ['3ffe000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3ffe010', 'a71e', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3ffe020', '8b35', '5aa2', '0000', '0000', '0010', '0000', '0000', '0000'], ['3fff000', 'b10c', '00ba', '0000', '0000', '1388', '0000', '0000', '0000'], ['3fff010', 'a71f', '0001', '0000', '0000', '1862', 'ce95', '26ba', '66c4'], ['3fff020', 'abbc', '5aa6', '0000', '0000', '0010', '0000', '0000', '0000'], []]


** ata-WDC_WD30EFRX-68EUZN0_WD-WCC4N7ZXC1E0-part1

TXG	TIME	TIMESTAMP	BLOCK ADDRESSES
108173	08 Feb 2018 02:24:11	1518053051	[360, 872, 5860494696, 5860495208]
108193	08 Feb 2018 02:25:59	1518053159	[264, 776, 5860494600, 5860495112]
108199	08 Feb 2018 02:26:30	1518053190	[312, 824, 5860494648, 5860495160]
108219	07 Mar 2018 16:44:43	1520437483	[472, 984, 5860494808, 5860495320]
108307	08 Mar 2018 15:58:41	1520521121	[408, 920, 5860494744, 5860495256]
108313	09 Mar 2018 14:25:03	1520601903	[456, 968, 5860494792, 5860495304]
108319	12 Mar 2018 17:33:00	1520872380	[504, 1016, 5860494840, 5860495352]
108325	14 Mar 2018 19:23:31	1521051811	[296, 808, 5860494632, 5860495144]
108331	15 Mar 2018 14:36:25	1521120985	[344, 856, 5860494680, 5860495192]
108337	15 Mar 2018 20:07:58	1521140878	[392, 904, 5860494728, 5860495240]



* cmds

physical read: zdb -R datapool 0.2:4200:8000:r | xxd | less




virtual read :zdb -Rv datapool 0:1034000:2200  | less

0:1034000:2200
          0 1 2 3 4 5 6 7   8 9 a b c d e f  0123456789abcdef
000000:  0a11020300000001  2000000000000000  ........ .......
000010:  0800000000000000  a07f010000000000  ................
000020:  0000000000000000  0000000000000000  ................
000030:  0000000000000000  0000000000000000  ................
000040:  1000000000000000  9081000000000000  ................
000050:  1000000000000000  9081020000000000  ................
000060:  1000000000000000  8081040000000000  ................
000070:  ff0007000f070a81  0000000000000000  ................
000080:  0000000000000000  0000000000000000  ................
000090:  2600000000000000  3500000000000000  &.......5.......
0000a0:  4dcd166897000000  8e9f55d0e60d0200  M..h......U.....
0000b0:  20d1cadcf15a9503  ef291eff35c2852f   ....Z...)..5../

on read device @ 0x967000 which is : zdb -Rv datapool 0.0:567000:2200 |less
(0x967000 - 0x400000)

1abc000 : (0x1ebc000-0x400000):      zdb -Rv datapool 0.0:1abc000:2200 | less



[10291.657879] typ-1: off:0x5e000 lsize:0x600 psize:0x600
[10291.657884] [+] : 0x5e000:0x1000 ashift:12,3,1
[10291.657886]  [=] cols = 2, firstdatacol = 1
[10291.657888]   [=] 1:0x1f000:0x1000
[10291.657890]   [=] 2:0x1f000:0x1000
[10291.657894] typ-1: off:0x41f000 lsize:0x1000 psize:0x1000
[10291.657900] vdev: 0x41f000:0x1000
[10291.658047] typ-0: off:0x0 lsize:0x0 psize:0x0
[10291.658053] typ-1: off:0x0 lsize:0x1000 psize:0x1000
[10291.658060] typ-1: off:0x5a000 lsize:0x1000 psize:0x1000
[10291.658064] [+] : 0x5a000:0x1000 ashift:12,3,1
[10291.658066]  [=] cols = 2, firstdatacol = 1
[10291.658068]   [=] 0:0x1e000:0x1000
[10291.658069]   [=] 1:0x1e000:0x1000
[10291.658073] typ-1: off:0x41e000 lsize:0x1000 psize:0x1000
[10291.658078] vdev: 0x41e000:0x1000
[10291.658170] typ-0: off:0x0 lsize:0x0 psize:0x0
[10291.658176] typ-1: off:0x0 lsize:0x1000 psize:0x1000
[10291.658183] typ-1: off:0x60000 lsize:0x1000 psize:0x1000
[10291.658187] [+] : 0x60000:0x1000 ashift:12,3,1
[10291.658190]  [=] cols = 2, firstdatacol = 1
[10291.658191]   [=] 0:0x20000:0x1000
[10291.658192]   [=] 1:0x20000:0x1000
[10291.658195] typ-1: off:0x420000 lsize:0x1000 psize:0x1000
[10291.658200] vdev: 0x420000:0x1000
